#!/bin/bash

SERVICE_NAME="fnaa"
SCRIPT_PATH="/etc/fnaa/fdu_network_auto_auth.py"
PYTHON="python"

start() {
    echo "starting $SERVICE_NAME ... ..."
    $PYTHON $SCRIPT_PATH &
    echo "$SERVICE_NAME started"
    exit 0;
}

stop() {
    echo "stopping $SERVICE_NAME ... ..."
    pkill -f $SCRIPT_PATH
    echo "$SERVICE_NAME stopped"
}

status() {
    if [ -e $SERVICE_NAME ]; then
	echo "$0 service started"
    else
	echo "$0 service stopped"
    fi
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    restart)
    stop
    start
    ;;
    status)
    status
    ;;
    *)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac
exit
